apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "cdn-web.imagePullSecretValue" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cdn-web.name" . }}
type: Opaque
data:
  {{- include "cdn-web.secretValues" . | nindent 2 }}
